stages:
  - build-package
  - deploy

build-package:
  stage: build-package
  tags:
    - fe-server
  services:
    - docker:20.10.23-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER_NAME -p $CI_REGISTRY_TOKEN $CI_REGISTRY
    - mkdir -p nginx
    - echo "$NGINX_CONF" > "nginx/nginx.conf"
    - echo "$MIME_TYPE" > "nginx/mime.types"
    - echo "$ENV" > "./.env"
  script:
    - DOCKER_BUILDKIT=1 docker build -t $CI_REGISTRY/mentee/mentee_2023.01/team/weat/gcell-frontend .
    - docker push $CI_REGISTRY/mentee/mentee_2023.01/team/weat/gcell-frontend
  after_script:
    - docker logout
  only:
    - main
    
deploy:
  stage: deploy
  tags:
    - fe-server
  services:
    - docker:20.10.23-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER_NAME -p $CI_REGISTRY_TOKEN $CI_REGISTRY
  script:
    - docker ps -a
    - docker-compose -f $FE_DOCKER_COMPOSE down
    - docker-compose -f $FE_DOCKER_COMPOSE up -d
    - docker ps -a
  after_script:
    - docker logout
  only:
    - main
